name: RubyGems Setup GPR
author: FreeAgent
description: Configure ruby gem to access for GPR (Github Package Registry)
inputs:
  token:
    description: "Token to access the GitHub package registry. Normally using secrets.github_token is enough."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup GPR
      shell: bash
      env:
        GEM_HOST_API_KEY: "Bearer ${{ inputs.token }}"
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials

        echo "GEM_HOST=https://rubygems.pkg.github.com/${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "GEM_HOST_API_KEY=$GEM_HOST_API_KEY" >> $GITHUB_ENV
